### ISSUE TITLE
support plantuml

### ISSUE THREAD

**Issue by huanggze** [Mivinci/hugo-theme-minima#17]
Would it be possible to integrate support for plantuml? Mermaid has some limits in describing `package` (or `namespace`). Adding plantuml would be a great alternate.

**Comment by Mivinci** [comment]
@huanggze I've read the documentation and will make time to do it.

**Comment by Mivinci** [comment]
@huanggze Hey pal. Sorry for the delay. I've studied how plantuml works and realized that plantuml needs a server side runtime aka the plantuml server. But Hugo is just a static site generator which means all the files generated by Hugo are static and live on browsers where plantuml can't. I've tried some tricky stuff like encoding the plantuml diagrams in the markdown file and sending them to the official plantuml online server, but since plantuml uses some kind of old ugly encoding technics that's gonna make Minima so clunky, I have to give it up. However, you can still use plantuml regardless of Hugo themes by writing the diagram in the [plantuml online server](https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000) and then using the link responded from the plantuml online server in your posts, just like how you insert an image into a markdown file.

**Comment by huanggze** [comment]
that's cool, thanks for the help!
