### ISSUE TITLE
`` sytanx cannot display correctly

### ISSUE THREAD

**Issue by Yuzuki-N** [Mivinci/hugo-theme-minima#4]
I  fond that words in the `` cannot be display correctly, the words in the ``, for instance,`THERE ARE SOMETHING` will be display as plain text

**Comment by Mivinci** [comment]
You mean words in "``" are shown without any style? This is because words in the "``" are  eventually  rendered in a `<code>` tag by Hugo. And I didn't write any CSS  for the `<code>` tag of the content, except its font-family.

Anyways, I've added background color for it. Thanks for your feedback.

**Comment by Mivinci** [comment]
You mean words in "``" are shown without any style? This is because words in the "``" are  eventually  rendered in a `<code>` tag by Hugo. And I didn't write any CSS  for the `<code>` tag of the content, except its font-family.

Anyways, I've added background color for it. Thanks for your feedback. @Yuzuki-N

**Comment by Mivinci** [comment]
You mean words in grave accent signs are shown without any style? This is because words in the them are eventually rendered in a `<code>` tag by Hugo. And I didn't write any CSS  for the `<code>` tag of the content, except its font-family.

Anyways, I've added background color for it. Thanks for your feedback. @Yuzuki-N
